name: Deploy

on:
  workflow_dispatch:
    inputs:
      fail:
        type: boolean

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building..."
      - run: sleep 15
      - run: echo "Deploying!"
      - if: inputs.fail
        run: exit 1
